# Server config
telegram:
  token: "5268346289:AAEjBhmqA1wyAjPMXd7S7mP2r_6t9pKp9TM"

mysql:
  host: 80.78.248.93
  port: 3306
  username: root
  password: NOBErd98%Ujcjjda1
  dbname: valute_bot
  connect_retry_ttl: 1
  connect_retry_max: 1024
  connect_check_ttl: 1

server_data:
  host: https://cbr-xml-daily.ru/daily_json.js
