# Server config
telegram:
  token: "5268346289:AAEjBhmqA1wyAjPMXd7S7mP2r_6t9pKp9TM"

mysql:
  host: 80.78.248.93
  port: 3306
  username: user_bot_valute
  password: Ak^VQ*3oPq1cvBL1
  dbname: telegram_bot_valute
  connect_retry_ttl: 1
  connect_retry_max: 1024
  connect_check_ttl: 1

server_data:
  host: https://cbr-xml-daily.ru/daily_json.js
