version: "3.3"
services:
  app:
    container_name: dockerdev
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DD_DB_HOST: mariadb
    depends_on:
      - database

  database:
    image: mariadb:10.3
    container_name: MariaDB
    restart: always
    ports:
      - ${PORT_MARIADB}:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
