version: "3.3"
services:
  app:
    container_name: app
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DD_DB_HOST: database
    depends_on:
      - database

  database:
    image: mariadb:10.3
    container_name: database
    restart: always
    ports:
      - ${PORT_DATABASE}:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TIMEZONE}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: ${PORT_DATABASE}
      PMA_ARBITRARY: 1
      TZ: ${TIMEZONE}
    restart: always
    ports:
      - ${PORT_PHPMYADMIN}:80